### ISSUE TITLE
Přesměrování odkazu na web z menu Draci.info

### ISSUE THREAD

**Issue by nemetmar** [Draciinfo/calendar-eshop#1]
@flaiming - nevím, jak tě assignnout, tak snad ti aspoň takhle přijde upozornění
https://draci.info/kalendar na http://kalendar.draci.info/ a https://draci.info/calendar na http://calendar.draci.info/

**Comment by flaiming** [comment]
Než to eXander přesměruje, upravil jsem text na stránkách https://draci.info/kalendar a https://draci.info/calendar .

**Comment by exander77** [comment]
Já jsem teď zmatený, ty jsi udělat úpravu přímo na serveru? Proč? Máš přístup ke gitu, ne? A pokud ano, tak nechápu, proč jsi tam nedal rovnou přesměrování?

**Comment by flaiming** [comment]
@exander77 Přístup ke gitu mám, ale nejsem si jistý, jaký je současný způsob nasazení z gitu a jestli se to vůbec používá, prostě to zatím dělám tak, jak jsem to dělal vždycky... Jinak jo, mohl jsem tam dát přesměrování rovnou. A nebo jak nad tím teď přemýšlím, úplně nejlepší bude prostě přímo v menu změnit odkaz.

**Comment by exander77** [comment]
@flaiming Jo, změnit odkaz v menu by možná bylo úplně nejlepší. Jinak stačí cokoliv dát pushnout v gitu do masteru a já to můžu snadno nasadit.

**Comment by flaiming** [comment]
Ok, mas to tam.
